import { matchPath } from 'react-router-dom';
import { routePaths } from '@/app/routePaths';

interface RouteMetadata {
  pattern: string;
  title: string;
}

const routeMetadata: RouteMetadata[] = [
  { pattern: routePaths.dashboard, title: 'Accueil' },
  { pattern: routePaths.search, title: 'Recherche globale' },
  { pattern: routePaths.profile, title: 'Profil' },
  { pattern: routePaths.settingsProfileObjectives, title: 'Profil et objectifs' },
  { pattern: routePaths.settingsAccountSync, title: 'Compte et synchronisation' },
  { pattern: routePaths.settingsPrivacyFriends, title: 'Confidentialité et amis' },
  { pattern: routePaths.settingsAppearanceAccessibility, title: 'Apparence et accessibilité' },
  { pattern: routePaths.settingsNotificationsRoutines, title: 'Rappels et routines' },
  { pattern: routePaths.settingsNutritionCalculations, title: 'Nutrition et calculs' },
  { pattern: routePaths.settingsAiPermissions, title: 'Autorisations et IA' },
  { pattern: routePaths.settingsDataBackup, title: 'Données et sauvegardes' },
  { pattern: routePaths.settingsAbout, title: 'À propos' },
  { pattern: routePaths.settingsAdvanced, title: 'Paramètres avancés' },
  { pattern: routePaths.dashboardCustomization, title: 'Affichage de l’Accueil' },
  { pattern: routePaths.syncPrototype, title: 'Compte de synchronisation' },
  { pattern: routePaths.accountDevices, title: 'Compte et appareils' },
  { pattern: routePaths.settings, title: 'Paramètres' },
  { pattern: routePaths.reminders, title: 'Rappels et routines' },
  { pattern: routePaths.barcodeScanner, title: 'Scanner un code-barres' },
  { pattern: routePaths.photoNutritionEstimate, title: 'Photo' },
  { pattern: routePaths.foodSelector, title: 'Ajouter un aliment' },
  { pattern: routePaths.addFood, title: 'Ajouter un aliment' },
  { pattern: routePaths.editFoodEntry, title: 'Modifier un aliment' },
  { pattern: routePaths.newFoodProduct, title: 'Créer un aliment' },
  { pattern: routePaths.editFoodProduct, title: 'Modifier un aliment' },
  { pattern: routePaths.foodProducts, title: 'Aliments' },
  { pattern: routePaths.foodSearch, title: 'Recherche alimentaire' },
  { pattern: routePaths.favoriteMeals, title: 'Repas favoris' },
  { pattern: routePaths.addRecipeToJournal, title: 'Ajouter une recette' },
  { pattern: routePaths.newRecipe, title: 'Créer une recette' },
  { pattern: routePaths.editRecipe, title: 'Modifier une recette' },
  { pattern: routePaths.recipes, title: 'Recettes' },
  { pattern: routePaths.food, title: 'Nutrition' },
  { pattern: routePaths.workoutSession, title: 'Séance de musculation' },
  { pattern: routePaths.newWorkoutTemplate, title: 'Créer une séance modèle' },
  { pattern: routePaths.editWorkoutTemplate, title: 'Modifier une séance modèle' },
  { pattern: routePaths.workoutTemplates, title: 'Séances modèles' },
  { pattern: routePaths.weeklyPlanning, title: 'Planning de musculation' },
  { pattern: routePaths.workoutSessions, title: 'Carnet de musculation' },
  { pattern: routePaths.strengthExerciseHistory, title: 'Historique de l’exercice' },
  { pattern: routePaths.newStrengthExercise, title: 'Créer un exercice' },
  { pattern: routePaths.editStrengthExercise, title: 'Modifier un exercice' },
  { pattern: routePaths.strengthExercises, title: 'Exercices' },
  { pattern: routePaths.enduranceTemplates, title: 'Modèles d’endurance' },
  { pattern: routePaths.addRunningActivity, title: 'Ajouter une course' },
  { pattern: routePaths.addSwimmingActivity, title: 'Ajouter une natation' },
  { pattern: routePaths.addStrengthActivity, title: 'Ajouter une activité de musculation' },
  { pattern: routePaths.addOtherActivity, title: 'Ajouter une activité' },
  { pattern: routePaths.editActivity, title: 'Modifier une activité' },
  { pattern: routePaths.addActivity, title: 'Ajouter une activité' },
  { pattern: routePaths.activities, title: 'Sport' },
  { pattern: routePaths.progression, title: 'Progression' },
  { pattern: routePaths.progressPhotoCompare, title: 'Comparer les photos de progression' },
  { pattern: routePaths.progressPhotos, title: 'Photos de progression' },
  { pattern: routePaths.weight, title: 'Poids' },
  { pattern: routePaths.history, title: 'Historique général' },
  { pattern: routePaths.analytics, title: 'Analyses' },
  { pattern: routePaths.reports, title: 'Rapport de progression' },
  { pattern: routePaths.goals, title: 'Objectifs et jalons' },
  { pattern: routePaths.weeklyReview, title: 'Bilan hebdomadaire' },
  { pattern: routePaths.rewards, title: 'Centre de récompenses' },
  { pattern: routePaths.friends, title: 'Amis et confidentialité' },
  { pattern: routePaths.backup, title: 'Sauvegarde' },
  { pattern: routePaths.trash, title: 'Corbeille' },
  { pattern: routePaths.calculationsInformation, title: 'Calculs et estimations' },
  { pattern: routePaths.privacy, title: 'Confidentialité' },
];

export function getRouteTitle(pathname: string): string {
  return routeMetadata.find(({ pattern }) => matchPath({ path: pattern, end: true }, pathname))?.title
    ?? 'SportPilot';
}
