import type { ExerciseDefinition } from '@/domain/models/strength';

export type CatalogExerciseSeed = Omit<ExerciseDefinition, 'createdAt' | 'updatedAt'>;

function catalogExercise(
  id: string,
  name: string,
  primaryMuscleGroup: ExerciseDefinition['primaryMuscleGroup'],
  secondaryMuscleGroups: ExerciseDefinition['secondaryMuscleGroups'],
  equipment: ExerciseDefinition['equipment'],
  category: ExerciseDefinition['category'],
  movementType: ExerciseDefinition['movementType'],
  loadUnit: ExerciseDefinition['loadUnit'],
  description?: string,
): CatalogExerciseSeed {
  return {
    id: `catalog:${id}`,
    name,
    primaryMuscleGroup,
    secondaryMuscleGroups,
    equipment,
    category,
    movementType,
    loadUnit,
    ...(description ? { description } : {}),
    source: 'catalog',
    isArchived: false,
  };
}

export const exerciseCatalog: readonly CatalogExerciseSeed[] = [
  catalogExercise('barbell-bench-press', 'Développé couché à la barre', 'pectorals', ['triceps', 'shoulders'], 'barbell', 'strength', 'compound', 'kg'),
  catalogExercise('incline-dumbbell-press', 'Développé incliné aux haltères', 'pectorals', ['triceps', 'shoulders'], 'dumbbells', 'strength', 'compound', 'kg'),
  catalogExercise('machine-chest-press', 'Développé pectoral à la machine', 'pectorals', ['triceps', 'shoulders'], 'machine', 'strength', 'compound', 'kg'),
  catalogExercise('cable-fly', 'Écarté à la poulie', 'pectorals', ['shoulders'], 'cable', 'strength', 'isolation', 'kg'),
  catalogExercise('push-up', 'Pompes', 'pectorals', ['triceps', 'shoulders'], 'bodyweight', 'bodyweight', 'compound', 'bodyweight'),
  catalogExercise('pull-up', 'Tractions pronation', 'back', ['biceps'], 'bodyweight', 'bodyweight', 'compound', 'bodyweight'),
  catalogExercise('lat-pulldown', 'Tirage vertical à la poulie', 'back', ['biceps'], 'cable', 'strength', 'compound', 'kg'),
  catalogExercise('barbell-row', 'Rowing barre', 'back', ['biceps', 'lowerBack'], 'barbell', 'strength', 'compound', 'kg'),
  catalogExercise('one-arm-dumbbell-row', 'Rowing unilatéral haltère', 'back', ['biceps'], 'dumbbells', 'strength', 'compound', 'kg'),
  catalogExercise('seated-cable-row', 'Tirage horizontal à la poulie', 'back', ['biceps'], 'cable', 'strength', 'compound', 'kg'),
  catalogExercise('overhead-press', 'Développé militaire à la barre', 'shoulders', ['triceps'], 'barbell', 'strength', 'compound', 'kg'),
  catalogExercise('dumbbell-shoulder-press', 'Développé épaules aux haltères', 'shoulders', ['triceps'], 'dumbbells', 'strength', 'compound', 'kg'),
  catalogExercise('lateral-raise', 'Élévations latérales', 'shoulders', [], 'dumbbells', 'strength', 'isolation', 'kg'),
  catalogExercise('rear-delt-fly', 'Oiseau aux haltères', 'shoulders', ['back'], 'dumbbells', 'strength', 'isolation', 'kg'),
  catalogExercise('face-pull', 'Face pull', 'shoulders', ['back'], 'cable', 'strength', 'isolation', 'kg'),
  catalogExercise('barbell-curl', 'Curl barre', 'biceps', [], 'barbell', 'strength', 'isolation', 'kg'),
  catalogExercise('dumbbell-curl', 'Curl haltères', 'biceps', [], 'dumbbells', 'strength', 'isolation', 'kg'),
  catalogExercise('hammer-curl', 'Curl marteau', 'biceps', [], 'dumbbells', 'strength', 'isolation', 'kg'),
  catalogExercise('cable-curl', 'Curl à la poulie', 'biceps', [], 'cable', 'strength', 'isolation', 'kg'),
  catalogExercise('triceps-pushdown', 'Extension triceps à la poulie', 'triceps', [], 'cable', 'strength', 'isolation', 'kg'),
  catalogExercise('skull-crusher', 'Barre au front', 'triceps', [], 'barbell', 'strength', 'isolation', 'kg'),
  catalogExercise('overhead-triceps-extension', 'Extension triceps au-dessus de la tête', 'triceps', [], 'dumbbells', 'strength', 'isolation', 'kg'),
  catalogExercise('dips', 'Dips', 'triceps', ['pectorals', 'shoulders'], 'bodyweight', 'bodyweight', 'compound', 'bodyweight'),
  catalogExercise('back-squat', 'Squat arrière à la barre', 'quadriceps', ['glutes', 'hamstrings', 'lowerBack'], 'barbell', 'strength', 'compound', 'kg'),
  catalogExercise('front-squat', 'Squat avant à la barre', 'quadriceps', ['glutes', 'abdominals'], 'barbell', 'strength', 'compound', 'kg'),
  catalogExercise('leg-press', 'Presse à cuisses', 'quadriceps', ['glutes', 'hamstrings'], 'machine', 'strength', 'compound', 'kg'),
  catalogExercise('leg-extension', 'Extension de jambes', 'quadriceps', [], 'machine', 'strength', 'isolation', 'kg'),
  catalogExercise('bulgarian-split-squat', 'Fentes bulgares', 'quadriceps', ['glutes', 'hamstrings'], 'dumbbells', 'strength', 'compound', 'kg'),
  catalogExercise('romanian-deadlift', 'Soulevé de terre roumain', 'hamstrings', ['glutes', 'lowerBack'], 'barbell', 'strength', 'compound', 'kg'),
  catalogExercise('leg-curl', 'Leg curl', 'hamstrings', [], 'machine', 'strength', 'isolation', 'kg'),
  catalogExercise('hip-thrust', 'Hip thrust à la barre', 'glutes', ['hamstrings'], 'barbell', 'strength', 'compound', 'kg'),
  catalogExercise('cable-kickback', 'Extension de hanche à la poulie', 'glutes', ['hamstrings'], 'cable', 'strength', 'isolation', 'kg'),
  catalogExercise('standing-calf-raise', 'Mollets debout', 'calves', [], 'machine', 'strength', 'isolation', 'kg'),
  catalogExercise('seated-calf-raise', 'Mollets assis', 'calves', [], 'machine', 'strength', 'isolation', 'kg'),
  catalogExercise('deadlift', 'Soulevé de terre', 'fullBody', ['back', 'glutes', 'hamstrings', 'lowerBack'], 'barbell', 'strength', 'compound', 'kg'),
  catalogExercise('kettlebell-swing', 'Kettlebell swing', 'fullBody', ['glutes', 'hamstrings', 'lowerBack'], 'kettlebell', 'conditioning', 'compound', 'kg'),
  catalogExercise('goblet-squat', 'Goblet squat', 'quadriceps', ['glutes', 'abdominals'], 'kettlebell', 'strength', 'compound', 'kg'),
  catalogExercise('plank', 'Planche', 'abdominals', ['lowerBack'], 'bodyweight', 'bodyweight', 'core', 'none'),
  catalogExercise('cable-crunch', 'Crunch à la poulie', 'abdominals', [], 'cable', 'strength', 'core', 'kg'),
  catalogExercise('hanging-leg-raise', 'Relevé de jambes suspendu', 'abdominals', [], 'bodyweight', 'bodyweight', 'core', 'bodyweight'),
  catalogExercise('back-extension', 'Extensions lombaires', 'lowerBack', ['glutes', 'hamstrings'], 'bodyweight', 'bodyweight', 'compound', 'bodyweight'),
  catalogExercise('farmer-carry', 'Marche du fermier', 'fullBody', ['shoulders', 'abdominals'], 'dumbbells', 'conditioning', 'carry', 'kg'),
  catalogExercise('band-pull-apart', 'Écarté avec élastique', 'shoulders', ['back'], 'resistanceBand', 'mobility', 'isolation', 'none'),
] as const;
